
const useFetch = async (method, url, options = {}) => {

    try {
        


    }catch(error) {
        console.log(error);
    }

}